### PR TITLE
Fix library when using glib 2.68.2

### PR DESCRIPTION
**Pull request by patrickelectric**
For more information, check: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1719

### CODE REVIEW

**Comment by Williangalvani** [comment]
This solves the build issues with gst-plugins-good on my machine

**Comment by acxz** [comment]
Instead of manually adding patches, have we thought about updating our submodule to be more up to date with the current upstream release version? That seems to be a more scalable solution.

**Comment by smagellan** [comment]
Debian testing switched to glib 2.70.2, no way to build QGC. Looks like the only reason for this fork to exist is this single Windows-specific commit: https://github.com/mavlink/gst-plugins-good/commit/9d782fad9dc0384ba86ecae64511c193f6149f93

**Comment by AndKe** [comment]
this needs attention/priority.

**Comment by bobosito000** [comment]
Might be a good idea to merge this and open a separate issue to make the submodule more up to date.

**Comment by AndKe** [comment]
I agree, it's well tested and proven to work.  @DonLakeFlyer ?

**Comment by patrickelectric** [comment]
@mrpollo I don't have merge powers on this repository, can you merge it ?

**Comment by DonLakeFlyer** [comment]
The submodule in mainline QGC repo is going to need to be brought up to this master to make this work I think.

**Comment by mrpollo** [comment]
Thanks @DonLakeFlyer, @patrickelectric already sent a PR for that which I merged https://github.com/mavlink/qgroundcontrol/pull/10132

**Pull request merged**
